name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust as needed

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --prod

      - name: Deploy to Apache Server
        run: |
          rsync -avzr --delete ./dist/ ubuntu@174.129.182.223:/var/www/html/
        env:
          RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD }} # Optional for password-based SSH
